name: kubectl CLI
description: GitHub Action to manage a kubernetes cluster
author: Ajeet Yadav <ajeetyadav164@gmail.com>
branding:
  icon: terminal
  color: blue
inputs:
  version:
    description: Version of the kubectl CLI to use
    required: false
    default: latest
runs:
  using: composite
  steps:
  - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    shell: bash
  - name: Configure kubectl CLI
    run: setup.sh
    shell: bash
    env:
      VERSION: ${{ inputs.version }}
